AllCops:
  TargetRubyVersion: 2.6
  NewCops: enable
  Exclude:
    - 'bin/**/*'
    - 'db/**/*'
    - 'config/**/*'
    - 'node_modules/**/*'
    - 'script/**/*'
    - 'support/**/*'
    - 'tmp/**/*'
    - 'test/**/*'
    - 'vendor/**/*'
    - 'spec/spec_helper.rb'

Style/Documentation:
  Enabled: false

Style/AsciiComments:
  AllowedChars: ['à', 'é', 'è', 'ë', 'ê', 'î', 'ï', 'ô', 'ù', 'ç', 'À', 'É', 'È', 'Ë', 'Ê', 'Î', 'Ï', 'Ô', 'Ù', 'Ç']

Layout/LineLength:
  Max: 100

Metrics/BlockLength:
  Exclude:
    - 'app/views/**/*'
    - 'spec/factories/*'
    - 'Guardfile'
  IgnoredMethods:
    - describe
    - it
    - resource
    - register
    - register_page
    - route_param
    - context
    - show
    - controller
    - namespace

Metrics/AbcSize:
  Exclude:
    - 'spec/models/restitution/inventaire/rapidite_spec.rb'
    - 'spec/models/restitution/controle/perseverance_spec.rb'
    - 'spec/models/restitution/inventaire/perseverance_spec.rb'
    - 'spec/models/restitution/tri/perseverance_spec.rb'
    - 'spec/models/restitution/tri/comprehension_consigne_spec.rb'
