Documentation:
  Enabled: false
AllCops:
  TargetRubyVersion: 2.6
  Exclude:
    - 'bin/**/*'
    - 'db/**/*'
    - 'config/**/*'
    - 'node_modules/**/*'
    - 'script/**/*'
    - 'support/**/*'
    - 'tmp/**/*'
    - 'test/**/*'
    - 'vendor/**/*'

Metrics/LineLength:
  Max: 100

Metrics/BlockLength:
  Exclude:
    - 'app/views/**/*'
    - 'spec/factories/*'
    - 'Guardfile'
  ExcludedMethods:
    - describe
    - it
    - resource
    - register
    - register_page
    - route_param
    - context
    - show
    - controller

Metrics/AbcSize:
  Exclude:
    - 'spec/models/evaluation/inventaire/rapidite_spec.rb'
    - 'spec/models/evaluation/controle/perseverance_spec.rb'
    - 'spec/models/evaluation/inventaire/perseverance_spec.rb'
    - 'spec/models/evaluation/tri/perseverance_spec.rb'
